---
image: alpine:edge

variables:
  key: keith.maxwell@gmail.com-5a1151a5.rsa

build:
  stage: build
  script:
    - printf '%s\n' "$abuild_key" > "$key"
    - ls -l "$key" # to see length of key / environment variable on disk
    - apk add ansible
    - ansible-playbook -i localhost, ./site.yaml
    - su abuild -c "buildrepo -d \"$PWD/public\" local"
    - cd public
    - tree -T "$CI_PROJECT_NAME — $CI_COMMIT_SHA" -H . --noreport -o index.html
  artifacts: { paths: [public], expire_in: 1 day }

pages:
  stage: deploy
  script: ["true"]
  artifacts: { paths: [public] }
  only: [master]
