---
image: alpine:edge

build:
  stage: build
  script:
    - |
      if test -n "$CI_DISPOSABLE_ENVIRONMENT" ; then
        adduser -D -G abuild chronos &&
        ln -s "$CI_PROJECT_DIR" /home/chronos/aports
      fi
    - apk add --quiet ansible
    - ansible-playbook -i localhost, ./site.yaml
    - chown -R chronos:abuild .
    - su chronos -c "buildrepo local"
    - cp -R /home/chronos/packages/. packages
    - cd packages
    - tree -T "$CI_PROJECT_NAME — $CI_COMMIT_SHA" -H . --noreport -o index.html
  artifacts: { paths: [packages], expire_in: 1 day }

pages:
  stage: deploy
  script: ["true"]
  artifacts: { paths: [packages] }
  only: [master]
