---
image: alpine:edge

variables:
  BUILD_CMD: buildrepo -a $CI_PROJECT_DIR -d $CI_PROJECT_DIR/public local

build:
  stage: build
  script:
    - find local -type l -exec sh -c 'i="$(readlink -f {})" && rm {} && cp -R
      "$i" {}' \;
    - |
      if test -n "$CI_DISPOSABLE_ENVIRONMENT" ; then
        adduser -D -G abuild chronos &&
        chown -R chronos:abuild . &&
        apk add --quiet ansible &&
        ANSIBLE_LOCALHOST_WARNING=False ansible-playbook -i , ./site.yaml
      fi
    - |
      if test "$LOGNAME" = chronos ; then
        $BUILD_CMD
      else
        su chronos -c '$BUILD_CMD'
      fi
    - cd public
    - tree -T "$CI_PROJECT_NAME — $CI_COMMIT_SHA" -H . --noreport -o index.html
  artifacts: { paths: [public], expire_in: 1 day }

pages:
  stage: deploy
  script: ["true"]
  artifacts: { paths: [public] }
  only: [master]
