---
image: alpine:edge

build:
  stage: build
  script:
    - grep 'docker\|lxc' /proc/1/cgroup && adduser -D -h "$PWD" -G abuild
      chronos
    - apk add ansible
    - ansible-playbook -i localhost, ./site.yaml
    - chown -R chronos:abuild .
    - su chronos -c "buildrepo local"
    - cd packages
    - tree -T "$CI_PROJECT_NAME — $CI_COMMIT_SHA" -H . --noreport -o index.html
  artifacts: { paths: [packages], expire_in: 1 day }

pages:
  stage: deploy
  script: ["true"]
  artifacts: { paths: [packages] }
  only: [master]
