---
- hosts: localhost
  connection: local
  become: true
  name: Setup to build packages
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    key: keith.maxwell@gmail.com-5a1151a5.rsa
    mirror: http://dl-cdn.alpinelinux.org/alpine
    packages:
      alpine-sdk: for the abuild commmand
      lua-aports: for the buildrepo command
      tree: to create index.html
    published_url: http://keith.maxwell.gitlab.io/aports-local
  tasks:
    - name: Check that the private key is available
      file: { path: "{{ key }}", state: file }
    - name: Install the public key so `apk index` succeeds
      copy:
        src: packages/{{ key }}.pub
        dest: /etc/apk/keys/{{ key }}.pub
    - name: Make repositories available for dependencies
      copy:
        dest: /etc/apk/repositories
        content: |
          {{ mirror }}/edge/main
          {{ mirror }}/edge/community
          {{ mirror }}/edge/testing
          {{ published_url }}/local
      notify: [Fetch repository indexes]
    - meta: flush_handlers
    - { name: Install packages, apk: { name: "{{ packages.keys() | list }}" } }
    - name: /etc/abuild.conf points to private key
      lineinfile:
        path: /etc/abuild.conf
        create: yes
        line: PACKAGER_PRIVKEY='{{ key | realpath }}'
  handlers:
    - name: Fetch repository indexes
      apk: { update_cache: yes }
# vim: ft=yaml.ansible
