---
- hosts: localhost
  connection: local
  become: true
  name: Setup to build packages
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    private_key: "{{ (public_key|basename|splitext)[0]|realpath }}"
    public_key: "{{ lookup('fileglob', 'packages/*.rsa.pub') }}"
    container: "{{ lookup('file', '/proc/1/cgroup') is search('docker|lxc') }}"
    mirror: http://dl-cdn.alpinelinux.org/alpine
    packages:
      alpine-sdk: for the abuild commmand
      lua-aports: for the buildrepo command
      tree: to create index.html
  tasks:
    - name: Check that a private key is available in the environment
      assert: { that: "{{ lookup('env', 'abuild_key')|length > 0 }}" }
      when: container
    - name: Check that a public key is available in the repository
      assert: { that: "{{ public_key|join('') is file }}" }
      when: container
    - name: Save the private key to disk
      copy:
        dest: "{{ private_key }}"
        content: "{{ lookup('env', 'abuild_key') }}\n"
      when: container
    - name: Install the public key so `apk index` succeeds
      copy:
        src: "{{ public_key }}"
        dest: /etc/apk/keys/{{ public_key | basename }}
    - name: Make repositories available for dependencies
      copy:
        dest: /etc/apk/repositories
        content: |
          {{ mirror }}/edge/main
          {{ mirror }}/edge/community
          {{ mirror }}/edge/testing
    - name: Fetch repository indexes
      apk: { update_cache: yes }
    - name: Install packages
      apk: { name: "{{ packages.keys() | list }}" }
    - name: /etc/abuild.conf points to private key
      lineinfile:
        path: /etc/abuild.conf
        create: yes
        line: PACKAGER_PRIVKEY='{{ private_key }}'
# vim: ft=yaml.ansible
