---
- name: Configure localhost to build Alpine Linux packages
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mirror: http://dl-cdn.alpinelinux.org/alpine
    packages:
      alpine-sdk: for the abuild commmand
      lua-aports: for the buildrepo command
      tree: to create index.html
  tasks:
    - name: Install packages (can clobber contents of /etc/abuild.conf)
      apk: { name: "{{ packages.keys() | list }}" }
      become: true
    - name: Install spdx-licenses-list to check licence=
      become: true
      apk:
        name: spdx-licenses-list
        repository: "{{ mirror }}/edge/community"
    - name: Make repositories available for dependencies
      copy:
        dest: /etc/apk/repositories
        content: |
          {{ mirror }}/edge/main
          {{ mirror }}/edge/community
          {{ mirror }}/edge/testing
      become: true
    - name: Fetch repository indexes
      apk: { update_cache: yes }
      become: true

- name: Configure localhost to build Alpine Linux packages if inside a container
  hosts: |-
    {{ lookup('file', '/proc/1/cgroup') is search('docker|lxc') |
       ternary('localhost', []) }}
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    private_key: "{{ (public_key|splitext)[0] }}"
    public_key: "{{ lookup('fileglob', '*.rsa.pub') }}"
  tasks:
    - name: Check that a private key is available in the environment
      assert: { that: "{{ lookup('env', 'abuild_key')|length > 0 }}" }
    - name: Check that a public key is available in the repository
      assert: { that: "{{ public_key|join('') is file }}" }
    - name: Save the private key to disk beside the public key
      copy:
        dest: "{{ private_key }}"
        content: "{{ lookup('env', 'abuild_key') }}\n"
    - name: /etc/abuild.conf (installed above) points to private key
      lineinfile:
        path: /etc/abuild.conf
        create: yes
        line: PACKAGER_PRIVKEY='{{ private_key }}'
    - name: Create the output directory
      file:
        path: "{{ lookup('env', 'CI_PROJECT_DIR') }}/public/user"
        state: directory
        owner: chronos
        group: abuild
        recurse: yes
      register: site_directory
    - name: Install the public key so `apk index` succeeds
      copy:
        src: "{{ public_key }}"
        dest: "{{ item }}/{{ public_key | basename }}"
      loop: [/etc/apk/keys, "{{ site_directory.path }}"]
# vim: ft=yaml.ansible
